lms/api/urls.py
from django.urls import path, include
from . import views

from rest_framework_nested import routers
from rest_framework_simplejwt.views import (
    TokenObtainPairView, 
    TokenRefreshView,
)
from drf_spectacular.views import (
    SpectacularAPIView, 
    SpectacularRedocView,
    SpectacularSwaggerView,
)

router = routers.SimpleRouter()

router.register(r'courses', views.CourseViewSet, basename= 'courses')

# A nested router for modules within courses
courses_router = routers.NestedSimpleRouter(router, r'courses', lookup= 'course')
courses_router.register(r'modules', views.ModuleViewSet, basename= 'course_modules')

courses_router.register(r'reviews', views.ReviewViewSet, basename= 'course_review')

courses_router.register(r'posts', views.PostViewSet, basename= 'course_posts')


urlpatterns = [
    # Token 
    path('token/', TokenObtainPairView.as_view(), name= 'token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name= 'token_refresh'),

    # API endpoints
    path('categories/', views.CategoryListAPIView.as_view(), name= 'category-list'),
    path('my_courses/', views.MyCoursesAPIView.as_view(), name= 'my-courses'),

    path('', include(router.urls)),
    path('', include(courses_router.urls)),    
    
    # Documentation
    path('schema/', SpectacularAPIView.as_view(), name= 'schema'),

    # UI
    path('schema/swagger_ui/', SpectacularSwaggerView.as_view(url_name= 'schema'), name= 'swagger_ui'),
    path('schema/redoc/', SpectacularRedocView.as_view(url_name= 'schema'), name= 'redoc'),

]

lms/courses/urls.py
from django.urls import path
from . import views
from .views import (CourseUpdateView, CourseDeleteView, LessonCreateView, LessonUpdateView, LessonDeleteView,
                    ModuleCreateView, ModuleUpdateView, ModuleDeleteView)

app_name = 'courses'
urlpatterns = [
    
    # COURSE CRUD URL.
    path(
        '<slug:course_slug>/manage/', 
        views.course_manage, 
        name= 'course_manage'
        ),
    path(
        'create/', 
        views.course_create, 
        name= 'course_create'
        ),
    path(
        '<slug:slug>/update/', 
        CourseUpdateView.as_view(), 
        name= 'course_update'
        ),
    path(
        '<slug:slug>/delete/', 
        CourseDeleteView.as_view(), 
        name= 'course_delete'
        ),

    # MODULE CRUD URL.
    path(
        '<slug:course_slug>/module/create/',
         ModuleCreateView.as_view(), 
         name= 'module_create'
         ),
    path(
        '<slug:course_slug>/module/<slug:module_slug>/update/',
         ModuleUpdateView.as_view(), 
         name= 'module_update'
         ),
    path(
        '<slug:course_slug>/module/<slug:module_slug>/delete/',
         ModuleDeleteView.as_view(), 
         name= 'module_delete'
         ),

    # LESSON CRUD URL.
    path(
        '<slug:course_slug>/module/<slug:module_slug>/lesson/create/', 
         LessonCreateView.as_view(), 
         name= 'lesson_create'
         ),
    path(
        '<slug:course_slug>/module/<slug:module_slug>/lesson/<slug:lesson_slug>/update/',
         LessonUpdateView.as_view(), 
         name= 'lesson_update'
         ),
    path(
        '<slug:course_slug>/module/<slug:module_slug>/lesson/<slug:lesson_slug>/delete/',
         LessonDeleteView.as_view(), 
         name= 'lesson_delete'
         ),

    path(
        '<slug:course_slug>/<slug:module_slug>/<slug:lesson_slug>/complete/', 
         views.mark_lesson_completion, 
         name= 'mark_lesson_complete'
         ),
    path(
        '<slug:course_slug>/<slug:module_slug>/<slug:lesson_slug>/', 
         views.lesson_detail, 
         name= 'lesson_details'
         ),

    
    
     # main url
    path('<slug:course_slug>/certificate/', 
        views.generate_certificate,
        name= 'generate_certificate'),
    
    path(
        'course_list/', 
        views.course_list, 
        name= 'course_list'
        ),
    path(
        '<slug:course_slug>/', 
        views.course_detail, 
        name= 'course_details'
        ),
    
    path(
        '',
        views.home,
        name= 'home',
    ),
    
]

lms/lms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth import views as auth_view

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # users app.
    path('accounts/', include('users.urls')),
    path('', include('users.urls')),

    # Enrollment app.
    path('enroll/', include('enrollment.urls')),

    # courses app.
    path('courses', include('courses.urls')),

    # Quiz app.
    path('quiz/', include('quiz.urls')),
    
    # Discussion app.
    path('discussion/', include('discussion.urls')),

    #  api
    path('api/<str:version>/', include('api.urls')),

    # tinymce
    path('tinymce/', include('tinymce.urls')),

    # Django password reset urls.
    path('accounts/password_reset/', 
         auth_view.PasswordResetView.as_view(template_name= 'users/password_reset_form.html'),
         name= 'password_reset'),
        
    path('accounts/password_reset/done/', 
         auth_view.PasswordResetDoneView.as_view(template_name= 'users/password_reset_done.html'),
         name= 'password_reset_done'),

    path('accounts/reset/<uidb64>/<token>/', 
         auth_view.PasswordResetConfirmView.as_view(template_name= 'users/password_reset_confirm.html'),
         name= 'password_reset_confirm'),

    path('accounts/reset/done/', 
         auth_view.PasswordResetCompleteView.as_view(template_name= 'users/password_reset_complete.html'),
         name= 'password_reset_complete'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATICFILES_DIRS)

lms/users/urls.py
from django.urls import path
from .import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name= 'register'),
    path('', views.user_login, name= 'login'),
    path('logout/', views.logout_user, name= 'logout'),
    path('profile/', views.profile, name= 'profile'),
    path('student_dashboard/', views.student_dashboard, name= 'student_dashboard'),
    path('instructor_dashboard/', views.Instructor_dashboard, name= 'instructor_dashboard'),
    path('notifications/read/<int:pk>/', views.mark_notification_as_read, name= 'mark_notification_as_read'),
]

lms/templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EduNova</title>
    <link rel="stylesheet" href="{% static 'style/lms.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>

    {{form.media}}

</head>
<body>
    <header>
        {% include 'nav.html' %}
    </header><br><hr><br>
    
    <main>
        {% if messages %}
            <ul class="messages">
                {% for i in messages %}
                    <li class="{{i.tags}}">{{i}}</li>
                {% endfor %}
            </ul>
        {% endif %}

        {% block content %}

            <section class="container-fluid bg-light text-dark p-5">
                <div class="container bg-light p-5 text-center">
                    <h1 class="display-4 fw-bold"> {{page_title}} </h1>
                    <p class="fs-4">
                        Your journey to knowledge begins here. Find your next course today.
                    </p>

                    <form action="{% url 'courses:course_list' %}" method="get" class="mt-4">

                        <div class="input-group mt-3 mb-3 mx-auto w-50">
                            <input type="text" name="q" class="form-control form-control-lg m-auto"
                            placeholder="Search for Course..." required>

                            <button type="submit" class="btn btn-primary mt-3 m-auto">Search</button>
                        </div>

                    </form>
                </div>
            </section>

            <section class="container text-center my-5">
                <div class="row">

                    <div class="col-md-4">
                        <h3>{{course_count}}</h3>
                        <p class="text-muted"> Online Courses </p>
                    </div>

                    <div class="col-md-4">
                        <h3> {{student_count}} </h3>
                        <p class="text-muted"> Happy Students. </p>
                    </div>

                    <div class="col-md-4">
                        <h3> {{instructor_count}} </h3>
                        <p class="text-muted"> Expert Instructors</p>
                    </div>

                </div>
            </section>

            <section class="container my-5">
                
                {% for category in categories %}
                    {% if category.courses.all %}
                    <h3 class="mb-4"> {{category.Name}} - Courses </h3>
                        <div class="row">
                            {% for course in category.courses.all|slice:":4" %}
                            
                            <div class="col-md-6 col-lg-4 mb-4 ">
                                <div class="card h-100">
                                    {% if course.thumbnail %}
                                        <img src=" {{course.thumbnail.url}} " alt=" {{course.title}} "
                                        class="card-img-top" thumbnail>
                                    
                                    {% else %}
                                        <img src="https://via.placeholder.com/120x90?text=No+Image" alt="No Thumbnail"
                                        class="card-img-top">

                                    {% endif %}

                                    <div class="card-body d-flex flex-column">
                                        <h5 class="card-title"> {{course.title}} </h5>
                                        <p class="card-text text-muted">
                                            <small>by {{course.instructor.username}} </small>
                                        </p>
                                        <a href="{{course.get_absolute_url}}" class="btn btn-primary">
                                            View Course
                                        </a>
                                    </div>

                                </div>
                            </div>

                            {% endfor %}
                        </div>
                        <hr class="my-5">

                    {% endif %}
                {% endfor %}
            </section>

        {% endblock content %}
    </main>

    <footer>
        <p id="foot">&copy; 2025 EduNova inc</p>
    </footer>
</body>
</html>

lms/templates/nav.html
{% load static %}
<nav class="navbar navbar-dark bg-dark border-bottom border-body fixed-top">
    
    <div class="container-fluid">
        
        <h1 class="navbar-brand"> <span class="bg-light text-dark fw-bold">Edu</span>Nova</h1>

        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar"
                                        aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        
        {% if unread_notifications_count == 0 %}
            <span class="badge bg-danger rounded-pill">
                {{unread_notifications_count}}
            </span>
        {% endif %}
        </button>
    
        <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" 
                                                        aria-labelledby="offcanvasDarkNavbarLabel">
            <div class="offcanvas-header d-flex justify-content-between">
                <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">

                    <a href="{% url 'users:profile' %}?section=notifications " class="nav-link">
                        <span class="bg-light text-dark fw-bold">Edu</span>Nova
                    </a>
                {% if unread_notifications_count >= 0 %}
                    <span class="badge bg-danger rounded-pill">
                        {{unread_notifications_count}}
                    </span>
                {% endif %}
                </h5>
            

                <button class="btn-close btn-close-white" type="button" data-bs-dismiss="offcanvas" 
                        aria-label="Close"></button>
            </div>
              
            <div class="offcanvas-body">
                
                <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                    <li class="nav-item">
                        <a href="{% url 'courses:home' %}" class="nav-link">
                            Home</a>
                    </li>

                    <li class="nav-item">
                        <a href="{% url 'courses:course_list' %}" class="nav-link">
                            Courses</a>
                    </li>
                    
                {% if request.user.is_authenticated %}     
                    {% if request.user.is_student %}

                    <li class="nav-item">
                        <a href="{% url 'users:student_dashboard' %}" class="nav-link">
                            My Learning</a>
                    </li>

                    {% elif request.user.is_instructor %}

                    <li class="nav-item">
                        <a href="{% url 'users:instructor_dashboard' %}" class="nav-link">
                            My Dashboard</a>
                    </li>

                    {% endif %}

                    <li class="nav-item">
                        <a href="{% url 'users:profile' %}" class="nav-link">
                            Profile</a>
                        <a href="{% url 'users:logout' %}" class="nav-link">
                            Logout</a>
                    </li>
                    
                {% else %} 

                    <li class="nav-item">
                        <a href="{% url 'users:register' %}" class="nav-link">
                            Register</a>
                        <a href="{% url 'users:login' %}" class="nav-link">
                            Login</a>
                    </li>

                </ul>
                {% endif %}
            </div>
            
        </div>
    </div>
</nav>